services:
  generate-app:
    build:
      context: ./services/keenOn-card-generate
      target: development
    container_name: generate-card-app-dev
    ports:
      - "4000:4000"
    volumes:
      - ./services/keenOn-card-generate:/app:cached
      - /app/node_modules
    env_file:
      - ./services/keenOn-card-generate/.env.development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - keenOn-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    stop_signal: SIGINT
    command: [ "sh", "-c", "./wait-for-db.sh && pnpm db:push && pnpm start:dev" ]

  postgres:
    image: postgres:14-alpine
    container_name: postgres-dev
    ports:
      - "6500:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:delegated
    env_file:
      - ./services/keenOn-card-generate/.env.development
    networks:
      - keenOn-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    stop_signal: SIGINT

  redis:
    image: redis:alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data:delegated
    env_file:
      - ./services/keenOn-card-generate/.env.development
    networks:
      - keenOn-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    stop_signal: SIGINT

networks:
  keenOn-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
