services:
  node-app:
    build:
      context: ./services/keenOn-card-generate
      target: development
    container_name: node-app-dev
    ports:
      - "8080:8080"
    volumes:
      - ./services/keenOn-card-generate:/app
      - /app/node_modules
    env_file:
      - .env.development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "grpcurl", "-plaintext", "localhost:50051", "list" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  translate-service:
    build:
      context: ./services/keenOn-card-translate
      target: development
    container_name: translate-service-dev
    ports:
      - "50051:50051"
    volumes:
      - ./services/keenOn-card-translate:/app
    networks:
      - my-network
    restart: unless-stopped

  compose-service:
    build:
      context: ./services/keenOn-card-compose
      target: development
    container_name: compose-service-dev
    ports:
      - "50052:50052"
    volumes:
      - ./services/keenOn-card-compose:/app
    networks:
      - my-network
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    container_name: postgres-dev
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - .env.development
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis-dev
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
    env_file:
      - .env.development
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  my-network:
    driver: bridge

volumes:
  progresDB:
  redisDB:
